### ISSUE TITLE
Flag React's dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#145]
In terms of our new templating engines sniffs. Eg.:

```
function createMarkup() {
  return {__html: 'First &middot; Second'};
}

function MyComponent() {
  return <div dangerouslySetInnerHTML={createMarkup()} />;
}
```

**Comment by nickdaugherty** [comment]
Can we prioritize this?

**Comment by GaryJones** [comment]
Is it just a case of working out which token this would appear as, then processing it when found, looking for the `dangerouslySetInnerHTML` string?

Warning or Error?
What severity?

**Comment by david-binda** [comment]
> Is it just a case of working out which token this would appear as, then processing it when found, looking for the dangerouslySetInnerHTML string?

Yeah, I think so. Simply flagging any appearance of `dangerouslySetInnerHTML` string (perhaps outside comment tokens) should do the job.

> Warning or Error?
> What severity?

I'd say the same which is used for reporting unescaped output in other sniffs. Used to be a blocker, not sure where we are at the moment :)

**Comment by rebeccahum** [comment]
I vote error since it is the same level as the error for JS string concatenation.

**Comment by rogertheriault** [comment]
I think for now we should just flag it in the same way we do `$_POST` - i.e. "_Requires visual inspection_" if the element is in use, even if it's using static text or the `DomPurify.sanitize` filter. And it should be flagged at the highest possible severity because XSS.

I'm presuming that if it is in use, it might even be more likely to be a bad unsafe use (or laziness). It's not hard to construct things in React without this - it's more likely to be used by folks getting HTML from a user, a DB, or somewhere not entirely trusted.

This page offers a bit more perspective on why it's got the weird parameter structure: https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html

If we get more advanced and can backtrace the `__html` parameter and it uses `sanitize` then possibly we can skip it, but I don't think it's necessary to go to that trouble **yet**, considering `sanitize` was only in use by 1 out of a few dozen repos on VIP Go when we started the audit.
