### ISSUE TITLE
Output from get_the_title() should be escaped

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#146]
Any output used from `get_the_title()` needs escaping, as per: https://developer.wordpress.org/reference/functions/get_the_title/#comment-2150 -- this should be flagged.

**Comment by rebeccahum** [comment]
Since it's listed as an "auto escaped function" here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/3f6ae0dd664d4813dcd580fdefccab45a4031589/WordPress/Sniff.php#L174 Is it best to remove it on the WPCS side or fork our one version of https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/Security/EscapeOutputSniff.php onto VIPCS? Or have another sniff on top of it for solely detecting built-in unescaped WP functions? @GaryJones thoughts?

**Comment by GaryJones** [comment]
I'd say close this Issue and re-open as an Issue / PR on WPCS.

Unrelated, but relevant: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1349

**Comment by rebeccahum** [comment]
Closing in favour of WPCS issue #1538: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1538
