### ISSUE TITLE
Kill "Overriding WordPress globals is prohibited" rule with fire.

### ISSUE THREAD

**Issue by mdbitz** [Automattic/VIP-Coding-Standards#398]
## What problem would the enhancement address for VIP?
This error is actually bad practice. If something a variable is a post Id or title, etc it is actually better to use $post_id $title instead of a different variation that could be mistyped or inconsistent.

🚫 Error: Overriding WordPress globals is prohibited. Found assignment to $post_id (WordPress.WP.GlobalVariablesOverride.OverrideProhibited).

## Describe the solution you'd like

Completely remove this rule from our ruleset

## Additional context

I'm actively seeing clients change their code to pstid, ttle, etc and this is bad for legibility and maintainability.

**Comment by GaryJones** [comment]
Could it be acceptable as a warning?

The positive use case would be when assignments are made to assignments from the global scope _accidentally_. It can be tricky to spot these logic bugs, so the assigning of a value to a variable of the same name in the same global name should be intentional. There are usually other names that can be used, such as `$id`, `$report_id`, `$custom_post_id` and so on, that don't happen to match exactly `$post_id`. 

We could make the violation message give suggestions as well:

🚫 Overriding WordPress globals should be done with care. Found assignment to $post_id. Consider using $custom_post_id if this was not intentional (WordPress.WP.GlobalVariablesOverride.OverrideProhibited).

**Comment by mdbitz** [comment]
Honestly I still don't see it as a concern. This alert to me is simple white noise that distracts from focus on other concerns.

If we did want to keep this as a warning, it should only flag if the code is in the global scope. E.g when there is a `global $post_id` statement in the function or we're in the global namespace. If we can't be that specific then the noise to signal ratio is to high for this to be useful.

**Comment by jrfnl** [comment]
> If we did want to keep this as a warning, it should only flag if the code is in the global scope. E.g when there is a global $post_id statement in the function or we're in the global namespace. If we can't be that specific then the noise to signal ratio is to high for this to be useful.

That's already the case and has been so since WPCS 1.1.0 (sept 2018). As this issue was opened in 2019, I can only wonder whether VIPCS was not up-to-date with WPCS at the time, but based on the contents of the `composer.json` file in the `0.4.0` VIPCS release, WPCS `1.*` was already being used.

From the [WPCS 1.1.0 changelog](https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/1.1.0):
> Various bugfixes for the WordPress.WP.GlobalVariablesOverride sniff:
> * Previously, the sniff only checked variables in the global namespace when a global statement would be encountered. As of now, all variable assignments in the global namespace will be checked.
> * Nested functions/closures/classes which don't import the global variable will now be skipped over when encountered within another function, preventing false positives.
> * Parameters in function declarations will no longer throw false positives.
> * The error message for assignments to a subkey of the $GLOBALS superglobal has been improved.
> * Various efficiency improvements.

As overriding a WP global variable is a legitimate concern as it will affect the functioning of WP for the rest of the page load when global variables don't have the expected value/type, I suggest closing this issue.

**Comment by GaryJones** [comment]
While there may be something we could do to further improve the DevEx and noise/signal ratio, it's not clear what that would be at this time, and any improvement to the sniff would be upstream anyway.
