### ISSUE TITLE
Unable to use v-html

### ISSUE THREAD

**Issue by amritansh24** [Automattic/VIP-Coding-Standards#434]
Hi there, 
I am using VIP-Minimum as standard in one of my WordPress Applications. 
However, I get warning `WordPressVIPMinimum.Security.Vuejs.RawHTMLDirectiveFound` whenever I use Vue's `v-html` tag. 

What would be the best suggestion to resolve this kind of warning?

**Comment by GaryJones** [comment]
Can you amend the value so that it doesn't need to contain HTML, and then use `{{ }}` ?

The v-html attribute allows HTML to be processed as markup rather than a plain text string, so if your variable held `<script>...</script>`, then it would be run, which is not ideal.

Difficult to give a concrete suggestion beyond that without knowing what the code and context is.

**Comment by amritansh24** [comment]
Hi Gary, thanks for the answer.
I will make these changes in my script & hopefully warning will vanish. 

Thanks.
