### ISSUE TITLE
Update PHPCS/WPCS dependencies

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/VIP-Coding-Standards#471]
## Bug Description
In composer.json, PHPCS is limited to 3.3.x (current = 3.5.4) and WPCS is limited to 2.1.x (current = 2.2.1).

**Comment by GaryJones** [comment]
Thanks Paul - I agree that we need to bump these.

**Comment by GaryJones** [comment]
Actually, looking at #472, and what we already have in composer.json, then VIPCS is already claiming compatibility with PHPCS 3.5 and WPCS 2.2, because of the `^` indicator in our versioning, which means we allow PHPCS up to anything below 4, and WPCS up to anything below 3.

You can locally run Composer updates for the specific packages you want to get the benefit of them - VIPCS is compatible as far as I know.
